use-auth-secret

response-origin-only-with-rfc5780

listening-port=3478
external-ip=187.127.143.52
fingerprint
realm=chat.tharavad.xyz
static-auth-secret=STATIC_AUTH_SECRET_HERE

total-quota=100
bps-capacity=0

no-cli
no-tls
no-dtls
